"""Added row

Revision ID: 3a51c5fe47b5
Revises: cb8434c45b50
Create Date: 2021-10-21 14:08:10.840066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a51c5fe47b5'
down_revision = 'cb8434c45b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('country_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'country_code')
    # ### end Alembic commands ###
