"""Rename column

Revision ID: cb17040874c1
Revises: 3a51c5fe47b5
Create Date: 2021-10-21 16:00:47.498894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb17040874c1'
down_revision = '3a51c5fe47b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('ip')
        batch_op.drop_column('external_ip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ip', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ip', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
